define.preload("g/alert",{
	"type":"dialog","cls":"dlg","node":{
		"type":"view","commands":{
			"close":{"type":"js","text":"dfish.close(this);"}
		},"node":{
			"type":"vert","id":"dlg_frame","height":"*","width":"*","nodes":[
				{
					"type":"horz","id":"dlg_head","cls":"dlg-head","height":"40","valign":"middle","nodes":[
						{"type":"dialog/title","id":"dlg_title","cls":"dlg-title","width":"*","wmin":10},{
							"type":"buttonbar","id":"dlg_head_oper","cls":"dlg-head-oper","width":"-1","align":"center","valign":"middle","pub":{"height":"*","width":"40"},"nodes":[
								{
									"tip":"关闭","cls":"x-dlg-close","on":{"click":"this.cmd('close');"},"icon":".i-dlg-close"
								}
							]
						}
					]
				},{
					"type":"vert","id":"dlg_trunk","cls":"dlg-trunk","height":"*","nodes":[
						{
							"type":"vert","height":"*","nodes":[
								{"type":"preload/body","id":"dlg_body","cls":"dlg-body","height":"*"}
							]
						}
					]
				}
			]
		}
	}
});